import React, { useState } from 'react';
import { AiCleanupSuggestion, ActiveTab, CleanerRule, DuplicateGroup, LargeFileItem, InstalledApp, DriveInfo } from '../types';
import { formatBytes } from '../data/mockSystemData';
import { 
  Sparkles, 
  Trash2, 
  Copy, 
  PackageX, 
  HardDrive, 
  ArrowRight, 
  RefreshCw, 
  ShieldCheck, 
  Zap, 
  TrendingDown, 
  CheckCircle2, 
  AlertCircle 
} from 'lucide-react';

interface AiSmartAdvisorProps {
  currentDrive: DriveInfo;
  rules: CleanerRule[];
  duplicates: DuplicateGroup[];
  largeFiles: LargeFileItem[];
  apps: InstalledApp[];
  onExecuteAction: (suggestion: AiCleanupSuggestion) => void;
  onExecuteBatchAll: () => void;
  setActiveTab: (tab: ActiveTab) => void;
}

export const AiSmartAdvisor: React.FC<AiSmartAdvisorProps> = ({
  currentDrive,
  rules,
  duplicates,
  largeFiles,
  apps,
  onExecuteAction,
  onExecuteBatchAll,
  setActiveTab,
}) => {
  const [isAnalyzing, setIsAnalyzing] = useState<boolean>(false);
  const [lastAnalyzedTime, setLastAnalyzedTime] = useState<string>('刚刚');

  // Compute live potential bytes from real current state
  const liveJunkBytes = rules.filter((r) => r.selected).reduce((acc, r) => acc + r.sizeBytes, 0);
  const liveDupBytes = duplicates.reduce(
    (acc, g) => acc + g.files.filter((f) => f.selected).length * g.sizeBytes,
    0
  );
  const bloatwareBytes = apps.filter((a) => a.isBloatware).reduce((acc, a) => acc + a.sizeBytes, 0);
  const topLargeFileBytes = largeFiles.slice(0, 2).reduce((acc, f) => acc + f.sizeBytes, 0);

  const totalPotentialBytes = liveJunkBytes + liveDupBytes + bloatwareBytes;

  // Default AI suggestions generated by heuristic rule engine
  const [suggestions, setSuggestions] = useState<AiCleanupSuggestion[]>([
    {
      id: 'ai-rec-1',
      category: 'duplicates',
      title: '清理完全冗余的超大系统镜像与离线安装包',
      potentialBytes: liveDupBytes > 0 ? liveDupBytes : 12.48 * 1024 * 1024 * 1024,
      priority: 'high',
      reason: 'AI 检测到在 Downloads 与 Backups 目录中存在完全一致的 Windows 11 ISO 与 CUDA 安装包，两级 SHA-256 校验码完全相同，可直接安全移除副本。',
      actionLabel: '一键清除重复副本',
      targetTab: 'duplicates',
    },
    {
      id: 'ai-rec-2',
      category: 'junk',
      title: '清空已失效的 Windows Update 补丁与浏览器渲染缓存',
      potentialBytes: liveJunkBytes > 0 ? liveJunkBytes : 8.85 * 1024 * 1024 * 1024,
      priority: 'high',
      reason: 'Windows 累积更新补丁已完成系统应用，其下载缓存与 Chrome/Edge 网页离线流媒体缓存占用巨大，清理后零破坏性。',
      actionLabel: '一键释放系统与浏览器缓存',
      targetTab: 'cleaner',
    },
    {
      id: 'ai-rec-3',
      category: 'apps',
      title: '静默卸载过期评估软件与 OEM 预装推广包',
      potentialBytes: bloatwareBytes > 0 ? bloatwareBytes : 5.25 * 1024 * 1024 * 1024,
      priority: 'medium',
      reason: '检测到已过期的评估软件 (AutoCAD) 以及 OEM 预装套件，调用 Win32 静默卸载命令可彻底清理其在 ProgramData 的留存数据。',
      actionLabel: '查看并卸载捆绑软件',
      targetTab: 'uninstaller',
    },
    {
      id: 'ai-rec-4',
      category: 'large_files',
      title: '审查长时间未启动的虚拟机镜像与大模型权重',
      potentialBytes: topLargeFileBytes,
      priority: 'low',
      reason: 'VirtualBox 虚拟硬盘 (.vmdk) 占用超 38GB 且已超 14 天无读写访问，建议归档至辅盘或挂载清理。',
      actionLabel: '透视大文件清单',
      targetTab: 'large_files',
    },
  ]);

  const handleRefreshAiAnalysis = async () => {
    setIsAnalyzing(true);
    try {
      const response = await fetch('/api/ai/analyze-cleanup', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          diskStats: {
            letter: currentDrive.letter,
            totalGB: currentDrive.totalBytes / (1024 * 1024 * 1024),
            usedGB: currentDrive.usedBytes / (1024 * 1024 * 1024),
            freeGB: currentDrive.freeBytes / (1024 * 1024 * 1024),
          },
          rules,
          duplicates,
          largeFiles,
          apps,
        }),
      });

      if (response.ok) {
        const json = await response.json();
        if (json.success && json.data?.recommendations?.length) {
          setSuggestions(json.data.recommendations);
        }
      }
    } catch (e) {
      console.log('AI analysis local fallback active');
    } finally {
      setTimeout(() => {
        setIsAnalyzing(false);
        const now = new Date();
        setLastAnalyzedTime(`${now.getHours().toString().padStart(2, '0')}:${now.getMinutes().toString().padStart(2, '0')}`);
      }, 800);
    }
  };

  const getCategoryBadge = (cat: string) => {
    switch (cat) {
      case 'duplicates':
        return { label: '重复文件', icon: Copy, color: 'text-purple-400 bg-purple-950/40 border-purple-800/40' };
      case 'junk':
        return { label: '系统垃圾', icon: Trash2, color: 'text-cyan-400 bg-cyan-950/40 border-cyan-800/40' };
      case 'apps':
        return { label: '无用软件', icon: PackageX, color: 'text-amber-400 bg-amber-950/40 border-amber-800/40' };
      default:
        return { label: '超大文件', icon: HardDrive, color: 'text-blue-400 bg-blue-950/40 border-blue-800/40' };
    }
  };

  return (
    <div className="bg-gradient-to-b from-slate-900/90 to-slate-900/60 border border-slate-700/80 rounded-2xl p-5 mb-6 shadow-lg shadow-cyan-950/20">
      {/* Top Banner */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 mb-4">
        <div>
          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded-lg bg-gradient-to-tr from-cyan-600 to-blue-500 text-white shadow-sm">
              <Sparkles className="w-4 h-4" />
            </div>
            <h2 className="text-base font-semibold text-white tracking-tight">
              AI 智能清理决策与潜力分析
            </h2>
            <span className="flex items-center gap-1 text-[11px] font-mono text-cyan-400 bg-cyan-950/50 border border-cyan-800/50 px-2 py-0.5 rounded">
              Gemini 3.8 Flash
            </span>
          </div>
          <p className="text-xs text-slate-400 mt-1 leading-relaxed">
            AI 综合评估 Windows 磁盘聚类、哈希查重比率与文件存活周期，推荐回报率最高的无损空间释放动作
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          <button
            onClick={handleRefreshAiAnalysis}
            disabled={isAnalyzing}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-slate-300 bg-slate-800/80 hover:bg-slate-700/80 border border-slate-700/80 rounded-xl transition-colors shadow-sm active:scale-95"
            title="重新运行 Gemini AI 空间潜力评估"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${isAnalyzing ? 'animate-spin text-cyan-400' : 'text-slate-400'}`} />
            <span>{isAnalyzing ? 'AI 分析中...' : '重新生成 AI 诊断'}</span>
          </button>

          <button
            onClick={onExecuteBatchAll}
            className="px-4 py-1.5 text-xs font-semibold rounded-xl bg-gradient-to-r from-cyan-400 to-blue-400 hover:from-cyan-300 hover:to-blue-300 text-slate-950 font-bold flex items-center gap-1.5 transition-all shadow-md shadow-cyan-500/20 active:scale-95 whitespace-nowrap"
          >
            <Zap className="w-3.5 h-3.5" />
            <span>一键执行推荐大扫除</span>
          </button>
        </div>
      </div>

      {/* 3 Executive Stat Tiles */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-4">
        <div className="p-3 bg-slate-950/60 border border-slate-800 rounded-xl">
          <div className="text-[11px] font-mono text-slate-400 flex items-center justify-between">
            <span>预估最大可释放潜力</span>
            <TrendingDown className="w-3.5 h-3.5 text-emerald-400" />
          </div>
          <div className="text-xl font-bold font-mono text-cyan-300 mt-1 tabular-nums">
            {formatBytes(totalPotentialBytes)}
          </div>
          <div className="text-[11px] font-mono text-slate-500 mt-0.5">
            涵盖垃圾缓存与完全重复副本
          </div>
        </div>

        <div className="p-3 bg-slate-950/60 border border-slate-800 rounded-xl">
          <div className="text-[11px] font-mono text-slate-400 flex items-center justify-between">
            <span>优先潜力类别</span>
            <Sparkles className="w-3.5 h-3.5 text-purple-400" />
          </div>
          <div className="text-sm font-bold text-slate-200 mt-1.5 truncate">
            重复大型镜像与补丁暂存
          </div>
          <div className="text-[11px] font-mono text-slate-500 mt-0.5">
            空间回报率最高，零工作环境破坏
          </div>
        </div>

        <div className="p-3 bg-slate-950/60 border border-slate-800 rounded-xl">
          <div className="text-[11px] font-mono text-slate-400 flex items-center justify-between">
            <span>操作安全性评估</span>
            <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
          </div>
          <div className="text-sm font-bold text-emerald-400 mt-1.5 flex items-center gap-1.5">
            <span>100% 极安全 (无损级)</span>
          </div>
          <div className="text-[11px] font-mono text-slate-500 mt-0.5">
            已开启 Win32 误删撤销缓冲保护
          </div>
        </div>
      </div>

      {/* Recommendations Cards Grid */}
      <div className="space-y-3">
        {suggestions.map((sug) => {
          const badge = getCategoryBadge(sug.category);
          const Icon = badge.icon;

          return (
            <div
              key={sug.id}
              className="p-3.5 bg-slate-950/50 hover:bg-slate-950/80 border border-slate-800 hover:border-slate-700/80 rounded-xl transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-3"
            >
              <div className="flex items-start gap-3 min-w-0">
                <div className="w-9 h-9 rounded-xl bg-slate-800/80 border border-slate-700/70 flex items-center justify-center shrink-0 mt-0.5">
                  <Icon className="w-4 h-4 text-cyan-400" />
                </div>

                <div className="min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="text-sm font-semibold text-slate-100">
                      {sug.title}
                    </span>
                    <span className={`text-[10px] font-mono border px-1.5 py-0.2 rounded shrink-0 ${badge.color}`}>
                      {badge.label}
                    </span>
                    {sug.priority === 'high' && (
                      <span className="text-[10px] font-mono text-rose-300 bg-rose-950/40 border border-rose-800/40 px-1.5 py-0.2 rounded">
                        高收益
                      </span>
                    )}
                  </div>

                  <p className="text-xs text-slate-400 mt-1 leading-relaxed">
                    {sug.reason}
                  </p>
                </div>
              </div>

              {/* Action */}
              <div className="flex items-center gap-3 shrink-0 self-end sm:self-center">
                <div className="text-right">
                  <span className="text-[11px] font-mono text-slate-500 block">释放空间</span>
                  <span className="text-sm font-bold font-mono text-cyan-300 tabular-nums">
                    +{formatBytes(sug.potentialBytes)}
                  </span>
                </div>

                <button
                  onClick={() => onExecuteAction(sug)}
                  className="px-3 py-1.5 text-xs font-semibold rounded-lg bg-slate-800 hover:bg-slate-700 text-cyan-300 hover:text-white border border-slate-700 hover:border-cyan-500/50 flex items-center gap-1.5 transition-all shadow-sm active:scale-95 whitespace-nowrap"
                >
                  <span>{sug.actionLabel}</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
